name: proteinmetrics

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - pandas
  - pytest
  - isort
  - jupyter
  - mypy
  - networkx
  - numpy
  - pandoc
  - PyYAML
  - scikit-learn
  - tqdm
  - pyprojroot
  - biopython
  - pytorch
  - plotly
  - natsort
  - mypy
  - pre-commit
  - pip
  - pip:
    - giotto-tda
    - grakel
    - hydra-core
    - fastwlk
    - fair-esm
