name: proteinggnnmetrics

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - pandas
  - pytest
  - isort
  - jupyter
  - mypy
  - networkx
  - numpy
  - pandoc
  - PyYAML
  - scikit-learn
  - tqdm
  - pyprojroot
  - biopython
  - pip
  - pip:
    - giotto-tda
    - grakel
