compute:
  n_jobs: 2
  n_parallel_runs: 10

random:
  state: 42

data:
  reduce_data: True

paths:
  multi_run_exp: "data/multi_run_exp"

eps_var:
  n_runs: 10

  eps:
    lower_bound: 4
    upper_bound: 11
    step: 1

  std:
    lower_bound: 0
    upper_bound: 100
    step: 2

  proteins:
    not_perturbed:
      lower_bound: 0
      upper_bound: 130

    perturbed:
      lower_bound: 130
      upper_bound: 200

imaging:
  protein_of_interest: 3
  images: "data/images"
  gifs: "data/images/gifs"
  gaussian_noise_path: "data/images/gaussian_noise"
  twist_path: "data/images/twist"
  shear_path: "data/images/shear"
  taper_path: "data/images/taper"
  mutation_path: "data/images/mutation"
