compute:
  n_jobs: 5
  n_parallel_runs: 5

random:
  state: 42

data:
  reduce_data: True

paths:
  experiment: "data/experiment_20220328-064300/"
  multi_run_exp: "data/multi_run_exp"

eps_var:
  n_runs: 10

  eps:
    lower_bound: 3
    upper_bound: 23
    step: 2

  std:
    lower_bound: 0
    upper_bound: 100
    step: 2

  proteins:
    not_perturbed:
      lower_bound: 0
      upper_bound: 130

    perturbed:
      lower_bound: 130
      upper_bound: 200
