compute:
  n_jobs: 5
  n_parallel_runs: 4

random:
  state: 42

data:
  reduce_data: True

paths:
  experiment: "data/experiment_20220328-064300/"
  multi_run_exp: "data/multi_run_exp"

eps_var:
  eps:
    lower_bound: 3
    upper_bound: 4
    step: 1

  std:
    lower_bound: 0
    upper_bound: 15
    step: 5

  proteins:
    not_perturbed:
      lower_bound: 0
      upper_bound: 2
      
    perturbed:
      lower_bound: 2
      upper_bound: 4