# This contains all the elements necessary to create the ensemble of experiments to run.

representations:
  - eps_graphs: [8, 16, 32]
  - knn_graphs: [2, 6, 8]
  - point_cloud: ["backbone", "CA"]
  - sequence: [""]

perturbations:
  [
    "twist",
    "shear",
    "taper",
    "mutate",
    "gaussian",
    "remove_edges",
    "create_edges",
    "rewire_edges",
    "add_nodes",
  ]

descriptors:
  [
    "persistence_diagram",
    "angles",
    "degree_histogram",
    "laplacian_spectrum",
    "clustering_histogram",
    "esm",
  ]

kernels:
  - persistence_fisher:
      - bandwidth: [0.5, 1, 1.5]
      - bandwidth_fisher: [0.5, 1, 1.5]
  - gaussian:
      - bandwidth: [0.5, 1, 1.5]
  - linear:
      - params: None
  - weisfeiler-lehman:
      - n_iter: [3, 5, 10]

organisms: ["humans", "ecoli"]

data:
  n_runs: 10
  sample_size: 100
  systematic_dir: "data/systematic"
  data_split_dir: "data/systematic/run_idx/"
  time_estimates_dir: "data/systematic/time/"

# compute:
#   representations:
#     graphs:
#     point_cloud:
#     sequence:
#     persistence_diagram:
#   perturbations:
#     geometric:
#     mutation:
#     graphs:
#   descriptors:
#     esm:
#     graph_descriptors:

#   # graph_pipeline_gaussian:
#   # graph_pipeline_linear:
#   # graph_pipeline_wlk:
#   # tda_pipeline:
#   # esm_pipeline:
#   # angles_pipeline:
