# This contains all the elements necessary to create the ensemble of experiments to run.

representations:
  - eps_graphs: [8, 16, 32]
  - knn_graphs: [2, 6, 8]
  - point_cloud: ["backbone", "CA"]
  - sequence: [""]

perturbations:
  [
    "twist",
    "shear",
    "taper",
    "mutate",
    "gaussian",
    "remove_edges",
    "create_edges",
    "rewire_edges",
    "add_nodes",
  ]

descriptors:
  [
    "persistence_diagram",
    "angles",
    "degree_histogram",
    "laplacian_spectrum",
    "clustering_histogram",
    "esm",
  ]

kernels:
  - persistence_fisher:
      - bandwidth:
          [
            1.e-05,
            1.e-04,
            1.e-03,
            1.e-02,
            1.e-01,
            1,
            1.e+02,
            1.e+03,
            1.e+04,
            1.e+05,
          ]
      - bandwidth_fisher:
          [
            1.e-05,
            1.e-04,
            1.e-03,
            1.e-02,
            1.e-01,
            1,
            1.e+02,
            1.e+03,
            1.e+04,
            1.e+05,
          ]
  - gaussian:
      - bandwidth:
          [
            1.e-05,
            1.e-04,
            1.e-03,
            1.e-02,
            1.e-01,
            1,
            1.e+02,
            1.e+03,
            1.e+04,
            1.e+05,
          ]
  - linear:
      - params: None
  - weisfeiler-lehman:
      - n_iter: [1, 2, 3, 5, 10]

organisms: ["humans", "ecoli"]

data:
  systematic_dir: "data/systematic"
  data_split_dir: "data/systematic/run_idx/"
  time_estimates_dir: "data/systematic/time/"
